version: '3'
services:
  postgres:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_PASSWORD: pPassW0
      POSTGRES_USER: pUseR
      POSTGRES_DB: spring_boot
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.10.2-management
    ports:
      - "15672:15672"
      - "25672:5672"

  mockserver:
    image: mockserver/mockserver
    ports:
      - "1080:1080"

  redis:
    image: redis:7.0.4
    ports:
      - "6379:6379"