spring.datasource.url: jdbc:postgresql://localhost:5432/spring_boot
spring.datasource.username: pUseR
spring.datasource.password: pPassW0

spring.jpa.open-in-view: false
server.port: 8181
spring.jpa.hibernate.ddl-auto: update
spring:
  application:
    name: bkit-solutions-study
  rabbitmq:
    port: 25672
    host: localhost
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

external-bank:
  url: http://bank.b

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      ExternalBankClient:
        connectTimeout: 10000
        readTimeout: 5000
        loggerLevel: full

amqp:
  notify-balance-queue: notify-balance-queue

logging:
  level:
    bkit:
      solutions:
        springbootstudy:
          clients: DEBUG
