spring.datasource.url: jdbc:postgresql://localhost:5432/spring_boot
spring.datasource.username: pUseR
spring.datasource.password: pPassW0

spring.jpa.open-in-view: false
server.port: 8181
spring.jpa.hibernate.ddl-auto: create-drop
init-data:
  accounts:
  - accountNumber: tu
    depositAmount: 0
  - accountNumber: vinh
    depositAmount: 2000
spring:
  application:
    name: bkit-solutions-study

external-bank:
  url: http://localhost:1080

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE