spring.datasource.url: jdbc:postgresql://localhost:5432/spring_boot
spring.datasource.username: pUseR
spring.datasource.password: pPassW0

spring.jpa.open-in-view: false
server.port: 8181
spring.jpa.hibernate.ddl-auto: update
init-data:
  accounts:
  - accountNumber: tu
    depositAmount: 0
  - accountNumber: vinh
    depositAmount: 2000
spring:
  application:
    name: bkit-solutions-study
  rabbitmq:
    port: 5672
    host: localhost

external-bank:
  url: http://localhost:1080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      ExternalBankClient:
        connectTimeout: 10000
        readTimeout: 5000
amqp:
  notify-balance-queue: notify-balance-queue
